baseURL = "https://opensource.suse.com/bci-docs/"
languageCode = "en-us"
title = "SUSE Linux BCI Documentation"
theme = "hugo-geekdoc"

[params]
  geekdocLogo = "suse_logo.svg"

  geekdocRepo = "https://github.com/SUSE/bci-docs"
  geekdocEditPath = "edit/main/"

  geekdocMenuBundle = true

  [params.geekdocContentLicense]
    name = "GNU Free Documentation License"
    link = "https://www.gnu.org/licenses/fdl-1.3.txt"

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor']
